services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./dados:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=auto_maia_mq
      - RABBITMQ_DEFAULT_PASS=auto_maia_mq
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    restart: always
    container_name: "auto_maia_cli_db"
    environment:
      - POSTGRES_DB=auto_maia_cli
      - POSTGRES_USER=auto_maia_cli
      - POSTGRES_PASSWORD=auto_maia_cli
    volumes:
      - ./postgres/data:/var/lib/postgresql